package net.fuyumori.stellashell;
import net.fuyumori.stellashell.ITaskChangeListener;
import android.os.ParcelFileDescriptor;
interface IDesktopBridge {
    void destroy() = 16777114;
    String settingsSnapshot() = 1;
    String applySettings(String desktop, String freeform) = 2;
    String launch(String component, int displayId, int mode) = 3;
    String taskSnapshot(int displayId) = 4;
    String taskOperation(int displayId, int taskId, String action, int left, int top, int right, int bottom) = 5;
    String launchProfile(String component, String resolved, int displayId, int mode, int left, int top, int right, int bottom, boolean newWindow) = 6;
    String back(int displayId) = 7;
    void setPrimaryMode(boolean enabled) = 8;
    String syncMouseRouting(int displayId, IBinder owner) = 9;
    String syncVirtualKeyboard(int displayId, boolean hide, IBinder owner) = 10;
    String captureDisplay(int displayId, in ParcelFileDescriptor output) = 11;
    String syncPrimaryScreen(int displayId, boolean off, IBinder owner) = 12;
    String moveWorkspaceTask(int source, int destination, int taskId, String component) = 14;
    void setWorkArea(int displayId, int left, int top, int right, int bottom) = 13;
    String displaySessions() = 15;
    String closeDisplaySession(int displayId, String identity) = 16;
    String syncWindowPins(boolean enabled, IBinder owner) = 17;
    String phoneTaskSnapshot() = 18;
    String focusPhoneTask(int taskId, String component) = 19;
    String phoneTaskOperation(int taskId, String component, String action, int left, int top, int right, int bottom) = 20;
    String snapshotDisplayScale(int displayId) = 21;
    String applyDisplayScale(int displayId, String identity, int percent) = 22;
    String checkedTaskOperation(int displayId, int taskId, String component, String action, int left, int top, int right, int bottom) = 23;
    String observeTaskChanges(ITaskChangeListener listener) = 24;
    void removeTaskObserver(ITaskChangeListener listener) = 25;
}
