pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories { google(); mavenCentral() }
}
rootProject.name = 'StellaShell'
include ':app', ':core', ':feature-search', ':platform-bridge'
project(':feature-search').projectDir = file('features/search')
project(':platform-bridge').projectDir = file('platform/bridge')
